/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSidebarRouteRouteImport } from './routes/_authenticated/_sidebar/route'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOnboardingCreateLeagueRouteImport } from './routes/_authenticated/onboarding/create-league'
import { Route as AuthenticatedSidebarTestRouteImport } from './routes/_authenticated/_sidebar/test'
import { Route as AuthenticatedSidebarProfileRouteImport } from './routes/_authenticated/_sidebar/profile'
import { Route as AuthAuthSignUpRouteImport } from './routes/_auth/auth/sign-up'
import { Route as AuthAuthSignInRouteImport } from './routes/_auth/auth/sign-in'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/_auth/auth/forgot-password'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/_public/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSidebarRouteRoute =
  AuthenticatedSidebarRouteRouteImport.update({
    id: '/_sidebar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingCreateLeagueRoute =
  AuthenticatedOnboardingCreateLeagueRouteImport.update({
    id: '/create-league',
    path: '/create-league',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedSidebarTestRoute =
  AuthenticatedSidebarTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AuthenticatedSidebarRouteRoute,
  } as any)
const AuthenticatedSidebarProfileRoute =
  AuthenticatedSidebarProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSidebarRouteRoute,
  } as any)
const AuthAuthSignUpRoute = AuthAuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthSignInRoute = AuthAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/home': typeof PublicHomeRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/sign-up': typeof AuthAuthSignUpRoute
  '/profile': typeof AuthenticatedSidebarProfileRoute
  '/test': typeof AuthenticatedSidebarTestRoute
  '/onboarding/create-league': typeof AuthenticatedOnboardingCreateLeagueRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof PublicHomeRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/sign-up': typeof AuthAuthSignUpRoute
  '/profile': typeof AuthenticatedSidebarProfileRoute
  '/test': typeof AuthenticatedSidebarTestRoute
  '/onboarding/create-league': typeof AuthenticatedOnboardingCreateLeagueRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_sidebar': typeof AuthenticatedSidebarRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_public/home': typeof PublicHomeRoute
  '/_auth/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/_auth/auth/sign-in': typeof AuthAuthSignInRoute
  '/_auth/auth/sign-up': typeof AuthAuthSignUpRoute
  '/_authenticated/_sidebar/profile': typeof AuthenticatedSidebarProfileRoute
  '/_authenticated/_sidebar/test': typeof AuthenticatedSidebarTestRoute
  '/_authenticated/onboarding/create-league': typeof AuthenticatedOnboardingCreateLeagueRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/home'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/test'
    | '/onboarding/create-league'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/test'
    | '/onboarding/create-league'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/_sidebar'
    | '/_authenticated/onboarding'
    | '/_public/home'
    | '/_auth/auth/forgot-password'
    | '/_auth/auth/sign-in'
    | '/_auth/auth/sign-up'
    | '/_authenticated/_sidebar/profile'
    | '/_authenticated/_sidebar/test'
    | '/_authenticated/onboarding/create-league'
    | '/_authenticated/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicHomeRoute: typeof PublicHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_sidebar': {
      id: '/_authenticated/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedSidebarRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/create-league': {
      id: '/_authenticated/onboarding/create-league'
      path: '/create-league'
      fullPath: '/onboarding/create-league'
      preLoaderRoute: typeof AuthenticatedOnboardingCreateLeagueRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_sidebar/test': {
      id: '/_authenticated/_sidebar/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedSidebarTestRouteImport
      parentRoute: typeof AuthenticatedSidebarRouteRoute
    }
    '/_authenticated/_sidebar/profile': {
      id: '/_authenticated/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedSidebarProfileRouteImport
      parentRoute: typeof AuthenticatedSidebarRouteRoute
    }
    '/_auth/auth/sign-up': {
      id: '/_auth/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthAuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/sign-in': {
      id: '/_auth/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthAuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/forgot-password': {
      id: '/_auth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthSignInRoute: typeof AuthAuthSignInRoute
  AuthAuthSignUpRoute: typeof AuthAuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthSignInRoute: AuthAuthSignInRoute,
  AuthAuthSignUpRoute: AuthAuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedSidebarRouteRouteChildren {
  AuthenticatedSidebarProfileRoute: typeof AuthenticatedSidebarProfileRoute
  AuthenticatedSidebarTestRoute: typeof AuthenticatedSidebarTestRoute
}

const AuthenticatedSidebarRouteRouteChildren: AuthenticatedSidebarRouteRouteChildren =
  {
    AuthenticatedSidebarProfileRoute: AuthenticatedSidebarProfileRoute,
    AuthenticatedSidebarTestRoute: AuthenticatedSidebarTestRoute,
  }

const AuthenticatedSidebarRouteRouteWithChildren =
  AuthenticatedSidebarRouteRoute._addFileChildren(
    AuthenticatedSidebarRouteRouteChildren,
  )

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingCreateLeagueRoute: typeof AuthenticatedOnboardingCreateLeagueRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingCreateLeagueRoute:
      AuthenticatedOnboardingCreateLeagueRoute,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSidebarRouteRoute: typeof AuthenticatedSidebarRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSidebarRouteRoute: AuthenticatedSidebarRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicHomeRoute: PublicHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
