/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as AuthenticatedSidebarRouteRouteImport } from './routes/_authenticated/_sidebar/route'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedLeaguesIndexRouteImport } from './routes/_authenticated/leagues/index'
import { Route as AuthenticatedOnboardingCreateLeagueRouteImport } from './routes/_authenticated/onboarding/create-league'
import { Route as AuthenticatedSidebarProfileRouteImport } from './routes/_authenticated/_sidebar/profile'
import { Route as AuthAuthSignUpRouteImport } from './routes/_auth/auth/sign-up'
import { Route as AuthAuthSignInRouteImport } from './routes/_auth/auth/sign-in'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/_auth/auth/forgot-password'
import { Route as AuthenticatedSidebarLeaguesSlugRouteRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/route'
import { Route as AuthenticatedSidebarLeaguesSlugIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/index'
import { Route as AuthenticatedSidebarLeaguesSlugTeamsRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/teams'
import { Route as AuthenticatedSidebarLeaguesSlugMembersRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/members'
import { Route as AuthenticatedSidebarLeaguesSlugInvitationsRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/invitations'
import { Route as AuthenticatedSidebarLeaguesSlugTeamsIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/teams/index'
import { Route as AuthenticatedSidebarLeaguesSlugSeasonsIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/seasons/index'
import { Route as AuthenticatedSidebarLeaguesSlugPlayersIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/players/index'
import { Route as AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/route'
import { Route as AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/teams/$teamId/index'
import { Route as AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/index'
import { Route as AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/players/$leaguePlayerId/index'
import { Route as AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRouteImport } from './routes/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/matches'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/_public/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSidebarRouteRoute =
  AuthenticatedSidebarRouteRouteImport.update({
    id: '/_sidebar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaguesIndexRoute =
  AuthenticatedLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingCreateLeagueRoute =
  AuthenticatedOnboardingCreateLeagueRouteImport.update({
    id: '/onboarding/create-league',
    path: '/onboarding/create-league',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSidebarProfileRoute =
  AuthenticatedSidebarProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSidebarRouteRoute,
  } as any)
const AuthAuthSignUpRoute = AuthAuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthSignInRoute = AuthAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSidebarLeaguesSlugRouteRoute =
  AuthenticatedSidebarLeaguesSlugRouteRouteImport.update({
    id: '/leagues/$slug',
    path: '/leagues/$slug',
    getParentRoute: () => AuthenticatedSidebarRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugIndexRoute =
  AuthenticatedSidebarLeaguesSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugTeamsRoute =
  AuthenticatedSidebarLeaguesSlugTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugMembersRoute =
  AuthenticatedSidebarLeaguesSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugInvitationsRoute =
  AuthenticatedSidebarLeaguesSlugInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugTeamsIndexRoute =
  AuthenticatedSidebarLeaguesSlugTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugTeamsRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute =
  AuthenticatedSidebarLeaguesSlugSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugPlayersIndexRoute =
  AuthenticatedSidebarLeaguesSlugPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute =
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteImport.update({
    id: '/seasons/$seasonSlug',
    path: '/seasons/$seasonSlug',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute =
  AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRouteImport.update({
    id: '/$teamId/',
    path: '/$teamId/',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugTeamsRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute =
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute =
  AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRouteImport.update({
    id: '/players/$leaguePlayerId/',
    path: '/players/$leaguePlayerId/',
    getParentRoute: () => AuthenticatedSidebarLeaguesSlugRouteRoute,
  } as any)
const AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute =
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () =>
      AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof PublicHomeRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/sign-up': typeof AuthAuthSignUpRoute
  '/profile': typeof AuthenticatedSidebarProfileRoute
  '/onboarding/create-league': typeof AuthenticatedOnboardingCreateLeagueRoute
  '/leagues': typeof AuthenticatedLeaguesIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/leagues/$slug': typeof AuthenticatedSidebarLeaguesSlugRouteRouteWithChildren
  '/leagues/$slug/invitations': typeof AuthenticatedSidebarLeaguesSlugInvitationsRoute
  '/leagues/$slug/members': typeof AuthenticatedSidebarLeaguesSlugMembersRoute
  '/leagues/$slug/teams': typeof AuthenticatedSidebarLeaguesSlugTeamsRouteWithChildren
  '/leagues/$slug/': typeof AuthenticatedSidebarLeaguesSlugIndexRoute
  '/leagues/$slug/seasons/$seasonSlug': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteWithChildren
  '/leagues/$slug/players': typeof AuthenticatedSidebarLeaguesSlugPlayersIndexRoute
  '/leagues/$slug/seasons': typeof AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute
  '/leagues/$slug/teams/': typeof AuthenticatedSidebarLeaguesSlugTeamsIndexRoute
  '/leagues/$slug/seasons/$seasonSlug/matches': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute
  '/leagues/$slug/players/$leaguePlayerId': typeof AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute
  '/leagues/$slug/seasons/$seasonSlug/': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute
  '/leagues/$slug/teams/$teamId': typeof AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof PublicHomeRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/sign-up': typeof AuthAuthSignUpRoute
  '/profile': typeof AuthenticatedSidebarProfileRoute
  '/onboarding/create-league': typeof AuthenticatedOnboardingCreateLeagueRoute
  '/leagues': typeof AuthenticatedLeaguesIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/leagues/$slug/invitations': typeof AuthenticatedSidebarLeaguesSlugInvitationsRoute
  '/leagues/$slug/members': typeof AuthenticatedSidebarLeaguesSlugMembersRoute
  '/leagues/$slug': typeof AuthenticatedSidebarLeaguesSlugIndexRoute
  '/leagues/$slug/players': typeof AuthenticatedSidebarLeaguesSlugPlayersIndexRoute
  '/leagues/$slug/seasons': typeof AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute
  '/leagues/$slug/teams': typeof AuthenticatedSidebarLeaguesSlugTeamsIndexRoute
  '/leagues/$slug/seasons/$seasonSlug/matches': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute
  '/leagues/$slug/players/$leaguePlayerId': typeof AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute
  '/leagues/$slug/seasons/$seasonSlug': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute
  '/leagues/$slug/teams/$teamId': typeof AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_sidebar': typeof AuthenticatedSidebarRouteRouteWithChildren
  '/_public/home': typeof PublicHomeRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_auth/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/_auth/auth/sign-in': typeof AuthAuthSignInRoute
  '/_auth/auth/sign-up': typeof AuthAuthSignUpRoute
  '/_authenticated/_sidebar/profile': typeof AuthenticatedSidebarProfileRoute
  '/_authenticated/onboarding/create-league': typeof AuthenticatedOnboardingCreateLeagueRoute
  '/_authenticated/leagues/': typeof AuthenticatedLeaguesIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_sidebar/leagues/$slug': typeof AuthenticatedSidebarLeaguesSlugRouteRouteWithChildren
  '/_authenticated/_sidebar/leagues/$slug/invitations': typeof AuthenticatedSidebarLeaguesSlugInvitationsRoute
  '/_authenticated/_sidebar/leagues/$slug/members': typeof AuthenticatedSidebarLeaguesSlugMembersRoute
  '/_authenticated/_sidebar/leagues/$slug/teams': typeof AuthenticatedSidebarLeaguesSlugTeamsRouteWithChildren
  '/_authenticated/_sidebar/leagues/$slug/': typeof AuthenticatedSidebarLeaguesSlugIndexRoute
  '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteWithChildren
  '/_authenticated/_sidebar/leagues/$slug/players/': typeof AuthenticatedSidebarLeaguesSlugPlayersIndexRoute
  '/_authenticated/_sidebar/leagues/$slug/seasons/': typeof AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute
  '/_authenticated/_sidebar/leagues/$slug/teams/': typeof AuthenticatedSidebarLeaguesSlugTeamsIndexRoute
  '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/matches': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute
  '/_authenticated/_sidebar/leagues/$slug/players/$leaguePlayerId/': typeof AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute
  '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/': typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute
  '/_authenticated/_sidebar/leagues/$slug/teams/$teamId/': typeof AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/accept-invitation/$invitationId'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/onboarding/create-league'
    | '/leagues'
    | '/onboarding'
    | '/leagues/$slug'
    | '/leagues/$slug/invitations'
    | '/leagues/$slug/members'
    | '/leagues/$slug/teams'
    | '/leagues/$slug/'
    | '/leagues/$slug/seasons/$seasonSlug'
    | '/leagues/$slug/players'
    | '/leagues/$slug/seasons'
    | '/leagues/$slug/teams/'
    | '/leagues/$slug/seasons/$seasonSlug/matches'
    | '/leagues/$slug/players/$leaguePlayerId'
    | '/leagues/$slug/seasons/$seasonSlug/'
    | '/leagues/$slug/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/accept-invitation/$invitationId'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/onboarding/create-league'
    | '/leagues'
    | '/onboarding'
    | '/leagues/$slug/invitations'
    | '/leagues/$slug/members'
    | '/leagues/$slug'
    | '/leagues/$slug/players'
    | '/leagues/$slug/seasons'
    | '/leagues/$slug/teams'
    | '/leagues/$slug/seasons/$seasonSlug/matches'
    | '/leagues/$slug/players/$leaguePlayerId'
    | '/leagues/$slug/seasons/$seasonSlug'
    | '/leagues/$slug/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/_sidebar'
    | '/_public/home'
    | '/accept-invitation/$invitationId'
    | '/_auth/auth/forgot-password'
    | '/_auth/auth/sign-in'
    | '/_auth/auth/sign-up'
    | '/_authenticated/_sidebar/profile'
    | '/_authenticated/onboarding/create-league'
    | '/_authenticated/leagues/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_sidebar/leagues/$slug'
    | '/_authenticated/_sidebar/leagues/$slug/invitations'
    | '/_authenticated/_sidebar/leagues/$slug/members'
    | '/_authenticated/_sidebar/leagues/$slug/teams'
    | '/_authenticated/_sidebar/leagues/$slug/'
    | '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug'
    | '/_authenticated/_sidebar/leagues/$slug/players/'
    | '/_authenticated/_sidebar/leagues/$slug/seasons/'
    | '/_authenticated/_sidebar/leagues/$slug/teams/'
    | '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/matches'
    | '/_authenticated/_sidebar/leagues/$slug/players/$leaguePlayerId/'
    | '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/'
    | '/_authenticated/_sidebar/leagues/$slug/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicHomeRoute: typeof PublicHomeRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_sidebar': {
      id: '/_authenticated/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedSidebarRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leagues/': {
      id: '/_authenticated/leagues/'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AuthenticatedLeaguesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/create-league': {
      id: '/_authenticated/onboarding/create-league'
      path: '/onboarding/create-league'
      fullPath: '/onboarding/create-league'
      preLoaderRoute: typeof AuthenticatedOnboardingCreateLeagueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_sidebar/profile': {
      id: '/_authenticated/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedSidebarProfileRouteImport
      parentRoute: typeof AuthenticatedSidebarRouteRoute
    }
    '/_auth/auth/sign-up': {
      id: '/_auth/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthAuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/sign-in': {
      id: '/_auth/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthAuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/forgot-password': {
      id: '/_auth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug': {
      id: '/_authenticated/_sidebar/leagues/$slug'
      path: '/leagues/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRouteImport
      parentRoute: typeof AuthenticatedSidebarRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/': {
      id: '/_authenticated/_sidebar/leagues/$slug/'
      path: '/'
      fullPath: '/leagues/$slug/'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/teams': {
      id: '/_authenticated/_sidebar/leagues/$slug/teams'
      path: '/teams'
      fullPath: '/leagues/$slug/teams'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/members': {
      id: '/_authenticated/_sidebar/leagues/$slug/members'
      path: '/members'
      fullPath: '/leagues/$slug/members'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugMembersRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/invitations': {
      id: '/_authenticated/_sidebar/leagues/$slug/invitations'
      path: '/invitations'
      fullPath: '/leagues/$slug/invitations'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugInvitationsRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/teams/': {
      id: '/_authenticated/_sidebar/leagues/$slug/teams/'
      path: '/'
      fullPath: '/leagues/$slug/teams/'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/seasons/': {
      id: '/_authenticated/_sidebar/leagues/$slug/seasons/'
      path: '/seasons'
      fullPath: '/leagues/$slug/seasons'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/players/': {
      id: '/_authenticated/_sidebar/leagues/$slug/players/'
      path: '/players'
      fullPath: '/leagues/$slug/players'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug': {
      id: '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug'
      path: '/seasons/$seasonSlug'
      fullPath: '/leagues/$slug/seasons/$seasonSlug'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/teams/$teamId/': {
      id: '/_authenticated/_sidebar/leagues/$slug/teams/$teamId/'
      path: '/$teamId'
      fullPath: '/leagues/$slug/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/': {
      id: '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/'
      path: '/'
      fullPath: '/leagues/$slug/seasons/$seasonSlug/'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/players/$leaguePlayerId/': {
      id: '/_authenticated/_sidebar/leagues/$slug/players/$leaguePlayerId/'
      path: '/players/$leaguePlayerId'
      fullPath: '/leagues/$slug/players/$leaguePlayerId'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRoute
    }
    '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/matches': {
      id: '/_authenticated/_sidebar/leagues/$slug/seasons/$seasonSlug/matches'
      path: '/matches'
      fullPath: '/leagues/$slug/seasons/$seasonSlug/matches'
      preLoaderRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRouteImport
      parentRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthSignInRoute: typeof AuthAuthSignInRoute
  AuthAuthSignUpRoute: typeof AuthAuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthSignInRoute: AuthAuthSignInRoute,
  AuthAuthSignUpRoute: AuthAuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedSidebarLeaguesSlugTeamsRouteChildren {
  AuthenticatedSidebarLeaguesSlugTeamsIndexRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsIndexRoute
  AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute
}

const AuthenticatedSidebarLeaguesSlugTeamsRouteChildren: AuthenticatedSidebarLeaguesSlugTeamsRouteChildren =
  {
    AuthenticatedSidebarLeaguesSlugTeamsIndexRoute:
      AuthenticatedSidebarLeaguesSlugTeamsIndexRoute,
    AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute:
      AuthenticatedSidebarLeaguesSlugTeamsTeamIdIndexRoute,
  }

const AuthenticatedSidebarLeaguesSlugTeamsRouteWithChildren =
  AuthenticatedSidebarLeaguesSlugTeamsRoute._addFileChildren(
    AuthenticatedSidebarLeaguesSlugTeamsRouteChildren,
  )

interface AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteChildren {
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute
}

const AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteChildren: AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteChildren =
  {
    AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute:
      AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugMatchesRoute,
    AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute:
      AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugIndexRoute,
  }

const AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteWithChildren =
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute._addFileChildren(
    AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteChildren,
  )

interface AuthenticatedSidebarLeaguesSlugRouteRouteChildren {
  AuthenticatedSidebarLeaguesSlugInvitationsRoute: typeof AuthenticatedSidebarLeaguesSlugInvitationsRoute
  AuthenticatedSidebarLeaguesSlugMembersRoute: typeof AuthenticatedSidebarLeaguesSlugMembersRoute
  AuthenticatedSidebarLeaguesSlugTeamsRoute: typeof AuthenticatedSidebarLeaguesSlugTeamsRouteWithChildren
  AuthenticatedSidebarLeaguesSlugIndexRoute: typeof AuthenticatedSidebarLeaguesSlugIndexRoute
  AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteWithChildren
  AuthenticatedSidebarLeaguesSlugPlayersIndexRoute: typeof AuthenticatedSidebarLeaguesSlugPlayersIndexRoute
  AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute: typeof AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute
  AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute: typeof AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute
}

const AuthenticatedSidebarLeaguesSlugRouteRouteChildren: AuthenticatedSidebarLeaguesSlugRouteRouteChildren =
  {
    AuthenticatedSidebarLeaguesSlugInvitationsRoute:
      AuthenticatedSidebarLeaguesSlugInvitationsRoute,
    AuthenticatedSidebarLeaguesSlugMembersRoute:
      AuthenticatedSidebarLeaguesSlugMembersRoute,
    AuthenticatedSidebarLeaguesSlugTeamsRoute:
      AuthenticatedSidebarLeaguesSlugTeamsRouteWithChildren,
    AuthenticatedSidebarLeaguesSlugIndexRoute:
      AuthenticatedSidebarLeaguesSlugIndexRoute,
    AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRoute:
      AuthenticatedSidebarLeaguesSlugSeasonsSeasonSlugRouteRouteWithChildren,
    AuthenticatedSidebarLeaguesSlugPlayersIndexRoute:
      AuthenticatedSidebarLeaguesSlugPlayersIndexRoute,
    AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute:
      AuthenticatedSidebarLeaguesSlugSeasonsIndexRoute,
    AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute:
      AuthenticatedSidebarLeaguesSlugPlayersLeaguePlayerIdIndexRoute,
  }

const AuthenticatedSidebarLeaguesSlugRouteRouteWithChildren =
  AuthenticatedSidebarLeaguesSlugRouteRoute._addFileChildren(
    AuthenticatedSidebarLeaguesSlugRouteRouteChildren,
  )

interface AuthenticatedSidebarRouteRouteChildren {
  AuthenticatedSidebarProfileRoute: typeof AuthenticatedSidebarProfileRoute
  AuthenticatedSidebarLeaguesSlugRouteRoute: typeof AuthenticatedSidebarLeaguesSlugRouteRouteWithChildren
}

const AuthenticatedSidebarRouteRouteChildren: AuthenticatedSidebarRouteRouteChildren =
  {
    AuthenticatedSidebarProfileRoute: AuthenticatedSidebarProfileRoute,
    AuthenticatedSidebarLeaguesSlugRouteRoute:
      AuthenticatedSidebarLeaguesSlugRouteRouteWithChildren,
  }

const AuthenticatedSidebarRouteRouteWithChildren =
  AuthenticatedSidebarRouteRoute._addFileChildren(
    AuthenticatedSidebarRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSidebarRouteRoute: typeof AuthenticatedSidebarRouteRouteWithChildren
  AuthenticatedOnboardingCreateLeagueRoute: typeof AuthenticatedOnboardingCreateLeagueRoute
  AuthenticatedLeaguesIndexRoute: typeof AuthenticatedLeaguesIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSidebarRouteRoute: AuthenticatedSidebarRouteRouteWithChildren,
  AuthenticatedOnboardingCreateLeagueRoute:
    AuthenticatedOnboardingCreateLeagueRoute,
  AuthenticatedLeaguesIndexRoute: AuthenticatedLeaguesIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicHomeRoute: PublicHomeRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
