/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedWithSidebarRouteImport } from './routes/_authenticated/_withSidebar'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOnboardingLeaguesRouteImport } from './routes/_authenticated/onboarding/leagues'
import { Route as AuthenticatedWithSidebarProfileRouteImport } from './routes/_authenticated/_withSidebar/profile'
import { Route as AuthenticatedWithSidebarLeaguesIndexRouteImport } from './routes/_authenticated/_withSidebar/leagues/index'
import { Route as AuthenticatedWithSidebarLeaguesCreateRouteImport } from './routes/_authenticated/_withSidebar/leagues/create'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/route'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugIndexRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/index'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/teams'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/settings'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugMembersRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/members'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/invites'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/index'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/players/index'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create-form'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/players/$playerId'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/route'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/index'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/index'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create'
import { Route as AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRouteImport } from './routes/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/create'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithSidebarRoute =
  AuthenticatedWithSidebarRouteImport.update({
    id: '/_withSidebar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingLeaguesRoute =
  AuthenticatedOnboardingLeaguesRouteImport.update({
    id: '/onboarding/leagues',
    path: '/onboarding/leagues',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWithSidebarProfileRoute =
  AuthenticatedWithSidebarProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedWithSidebarRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesIndexRoute =
  AuthenticatedWithSidebarLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => AuthenticatedWithSidebarRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesCreateRoute =
  AuthenticatedWithSidebarLeaguesCreateRouteImport.update({
    id: '/leagues/create',
    path: '/leagues/create',
    getParentRoute: () => AuthenticatedWithSidebarRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteImport.update({
    id: '/leagues/$leagueSlug',
    path: '/leagues/$leagueSlug',
    getParentRoute: () => AuthenticatedWithSidebarRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRouteImport.update({
    id: '/seasons/create-form',
    path: '/seasons/create-form',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRouteImport.update({
    id: '/seasons/create',
    path: '/seasons/create',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
  } as any)
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteImport.update(
    {
      id: '/seasons/$seasonSlug',
      path: '/seasons/$seasonSlug',
      getParentRoute: () => AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute,
    } as any,
  )
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute,
    } as any,
  )
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRouteImport.update(
    {
      id: '/matches/',
      path: '/matches/',
      getParentRoute: () =>
        AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute,
    } as any,
  )
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRouteImport.update(
    {
      id: '/matches/elo-create',
      path: '/matches/elo-create',
      getParentRoute: () =>
        AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute,
    } as any,
  )
const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRouteImport.update(
    {
      id: '/matches/create',
      path: '/matches/create',
      getParentRoute: () =>
        AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/profile': typeof AuthenticatedWithSidebarProfileRoute
  '/onboarding/leagues': typeof AuthenticatedOnboardingLeaguesRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/leagues/$leagueSlug': typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteWithChildren
  '/leagues/create': typeof AuthenticatedWithSidebarLeaguesCreateRoute
  '/leagues/': typeof AuthenticatedWithSidebarLeaguesIndexRoute
  '/leagues/$leagueSlug/invites': typeof AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute
  '/leagues/$leagueSlug/members': typeof AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute
  '/leagues/$leagueSlug/settings': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute
  '/leagues/$leagueSlug/teams': typeof AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute
  '/leagues/$leagueSlug/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteWithChildren
  '/leagues/$leagueSlug/players/$playerId': typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute
  '/leagues/$leagueSlug/seasons/create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute
  '/leagues/$leagueSlug/seasons/create-form': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute
  '/leagues/$leagueSlug/players/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute
  '/leagues/$leagueSlug/seasons/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/matches/create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/matches/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/profile': typeof AuthenticatedWithSidebarProfileRoute
  '/onboarding/leagues': typeof AuthenticatedOnboardingLeaguesRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/leagues/create': typeof AuthenticatedWithSidebarLeaguesCreateRoute
  '/leagues': typeof AuthenticatedWithSidebarLeaguesIndexRoute
  '/leagues/$leagueSlug/invites': typeof AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute
  '/leagues/$leagueSlug/members': typeof AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute
  '/leagues/$leagueSlug/settings': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute
  '/leagues/$leagueSlug/teams': typeof AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute
  '/leagues/$leagueSlug': typeof AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute
  '/leagues/$leagueSlug/players/$playerId': typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute
  '/leagues/$leagueSlug/seasons/create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute
  '/leagues/$leagueSlug/seasons/create-form': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute
  '/leagues/$leagueSlug/players': typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute
  '/leagues/$leagueSlug/seasons': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/matches/create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute
  '/leagues/$leagueSlug/seasons/$seasonSlug/matches': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_withSidebar': typeof AuthenticatedWithSidebarRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/_withSidebar/profile': typeof AuthenticatedWithSidebarProfileRoute
  '/_authenticated/onboarding/leagues': typeof AuthenticatedOnboardingLeaguesRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug': typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteWithChildren
  '/_authenticated/_withSidebar/leagues/create': typeof AuthenticatedWithSidebarLeaguesCreateRoute
  '/_authenticated/_withSidebar/leagues/': typeof AuthenticatedWithSidebarLeaguesIndexRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/invites': typeof AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/members': typeof AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/settings': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/teams': typeof AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteWithChildren
  '/_authenticated/_withSidebar/leagues/$leagueSlug/players/$playerId': typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create-form': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/players/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute
  '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/': typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/onboarding/leagues'
    | '/onboarding/'
    | '/leagues/$leagueSlug'
    | '/leagues/create'
    | '/leagues/'
    | '/leagues/$leagueSlug/invites'
    | '/leagues/$leagueSlug/members'
    | '/leagues/$leagueSlug/settings'
    | '/leagues/$leagueSlug/teams'
    | '/leagues/$leagueSlug/'
    | '/leagues/$leagueSlug/seasons/$seasonSlug'
    | '/leagues/$leagueSlug/players/$playerId'
    | '/leagues/$leagueSlug/seasons/create'
    | '/leagues/$leagueSlug/seasons/create-form'
    | '/leagues/$leagueSlug/players/'
    | '/leagues/$leagueSlug/seasons/'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/matches/create'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/onboarding/leagues'
    | '/onboarding'
    | '/leagues/create'
    | '/leagues'
    | '/leagues/$leagueSlug/invites'
    | '/leagues/$leagueSlug/members'
    | '/leagues/$leagueSlug/settings'
    | '/leagues/$leagueSlug/teams'
    | '/leagues/$leagueSlug'
    | '/leagues/$leagueSlug/players/$playerId'
    | '/leagues/$leagueSlug/seasons/create'
    | '/leagues/$leagueSlug/seasons/create-form'
    | '/leagues/$leagueSlug/players'
    | '/leagues/$leagueSlug/seasons'
    | '/leagues/$leagueSlug/seasons/$seasonSlug'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/matches/create'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create'
    | '/leagues/$leagueSlug/seasons/$seasonSlug/matches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_withSidebar'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/_withSidebar/profile'
    | '/_authenticated/onboarding/leagues'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug'
    | '/_authenticated/_withSidebar/leagues/create'
    | '/_authenticated/_withSidebar/leagues/'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/invites'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/members'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/settings'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/teams'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/players/$playerId'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create-form'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/players/'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/create'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create'
    | '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_withSidebar': {
      id: '/_authenticated/_withSidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWithSidebarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/leagues': {
      id: '/_authenticated/onboarding/leagues'
      path: '/onboarding/leagues'
      fullPath: '/onboarding/leagues'
      preLoaderRoute: typeof AuthenticatedOnboardingLeaguesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_withSidebar/profile': {
      id: '/_authenticated/_withSidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedWithSidebarProfileRouteImport
      parentRoute: typeof AuthenticatedWithSidebarRoute
    }
    '/_authenticated/_withSidebar/leagues/': {
      id: '/_authenticated/_withSidebar/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesIndexRouteImport
      parentRoute: typeof AuthenticatedWithSidebarRoute
    }
    '/_authenticated/_withSidebar/leagues/create': {
      id: '/_authenticated/_withSidebar/leagues/create'
      path: '/leagues/create'
      fullPath: '/leagues/create'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesCreateRouteImport
      parentRoute: typeof AuthenticatedWithSidebarRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug'
      path: '/leagues/$leagueSlug'
      fullPath: '/leagues/$leagueSlug'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteImport
      parentRoute: typeof AuthenticatedWithSidebarRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/'
      path: '/'
      fullPath: '/leagues/$leagueSlug/'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/teams': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/teams'
      path: '/teams'
      fullPath: '/leagues/$leagueSlug/teams'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/settings': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/settings'
      path: '/settings'
      fullPath: '/leagues/$leagueSlug/settings'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/members': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/members'
      path: '/members'
      fullPath: '/leagues/$leagueSlug/members'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugMembersRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/invites': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/invites'
      path: '/invites'
      fullPath: '/leagues/$leagueSlug/invites'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/'
      path: '/seasons'
      fullPath: '/leagues/$leagueSlug/seasons/'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/players/': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/players/'
      path: '/players'
      fullPath: '/leagues/$leagueSlug/players/'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create-form': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create-form'
      path: '/seasons/create-form'
      fullPath: '/leagues/$leagueSlug/seasons/create-form'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/create'
      path: '/seasons/create'
      fullPath: '/leagues/$leagueSlug/seasons/create'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/players/$playerId': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/leagues/$leagueSlug/players/$playerId'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug'
      path: '/seasons/$seasonSlug'
      fullPath: '/leagues/$leagueSlug/seasons/$seasonSlug'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/'
      path: '/'
      fullPath: '/leagues/$leagueSlug/seasons/$seasonSlug/'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/'
      path: '/matches'
      fullPath: '/leagues/$leagueSlug/seasons/$seasonSlug/matches/'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create'
      path: '/matches/elo-create'
      fullPath: '/leagues/$leagueSlug/seasons/$seasonSlug/matches/elo-create'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute
    }
    '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/create': {
      id: '/_authenticated/_withSidebar/leagues/$leagueSlug/seasons/$seasonSlug/matches/create'
      path: '/matches/create'
      fullPath: '/leagues/$leagueSlug/seasons/$seasonSlug/matches/create'
      preLoaderRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRouteImport
      parentRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute
    }
  }
}

interface AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteChildren {
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute
}

const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteChildren: AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteChildren =
  {
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugIndexRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesCreateRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesEloCreateRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugMatchesIndexRoute,
  }

const AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteWithChildren =
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute._addFileChildren(
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteChildren,
  )

interface AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteChildren {
  AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteWithChildren
  AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute
}

const AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteChildren: AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteChildren =
  {
    AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugInvitesRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugMembersRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSettingsRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugTeamsRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugIndexRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsSeasonSlugRouteRouteWithChildren,
    AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugPlayersPlayerIdRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsCreateFormRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugPlayersIndexRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugSeasonsIndexRoute,
  }

const AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteWithChildren =
  AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute._addFileChildren(
    AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteChildren,
  )

interface AuthenticatedWithSidebarRouteChildren {
  AuthenticatedWithSidebarProfileRoute: typeof AuthenticatedWithSidebarProfileRoute
  AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute: typeof AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteWithChildren
  AuthenticatedWithSidebarLeaguesCreateRoute: typeof AuthenticatedWithSidebarLeaguesCreateRoute
  AuthenticatedWithSidebarLeaguesIndexRoute: typeof AuthenticatedWithSidebarLeaguesIndexRoute
}

const AuthenticatedWithSidebarRouteChildren: AuthenticatedWithSidebarRouteChildren =
  {
    AuthenticatedWithSidebarProfileRoute: AuthenticatedWithSidebarProfileRoute,
    AuthenticatedWithSidebarLeaguesLeagueSlugRouteRoute:
      AuthenticatedWithSidebarLeaguesLeagueSlugRouteRouteWithChildren,
    AuthenticatedWithSidebarLeaguesCreateRoute:
      AuthenticatedWithSidebarLeaguesCreateRoute,
    AuthenticatedWithSidebarLeaguesIndexRoute:
      AuthenticatedWithSidebarLeaguesIndexRoute,
  }

const AuthenticatedWithSidebarRouteWithChildren =
  AuthenticatedWithSidebarRoute._addFileChildren(
    AuthenticatedWithSidebarRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWithSidebarRoute: typeof AuthenticatedWithSidebarRouteWithChildren
  AuthenticatedOnboardingLeaguesRoute: typeof AuthenticatedOnboardingLeaguesRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWithSidebarRoute: AuthenticatedWithSidebarRouteWithChildren,
  AuthenticatedOnboardingLeaguesRoute: AuthenticatedOnboardingLeaguesRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
