name: Issue Triage (OpenCode)

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to triage"
        required: true
        type: number

jobs:
  triage:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (!contains(github.event.issue.labels.*.name, 'triaged') &&
       !contains(github.event.issue.labels.*.name, 'skip-triage'))
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      issues: write
      id-token: write
    env:
      ISSUE_NUMBER: ${{ github.event.inputs.issue_number || github.event.issue.number }}
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Read prompt template
        id: prompt
        run: |
          PROMPT=$(cat .github/opencode-prompts/triage-issue.md)
          PROMPT="${PROMPT//\$ISSUE_NUMBER/${{ env.ISSUE_NUMBER }}}"
          echo "prompt<<EOF" >> $GITHUB_OUTPUT
          echo "$PROMPT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Triage issue with OpenCode
        id: opencode
        uses: opencode-ai/action@v1
        with:
          model: zen/kimi-k2.5
          prompt: ${{ steps.prompt.outputs.prompt }}
          allowed_tools: |
            Bash(gh issue view:*)
            Glob
            Grep
            Read
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_ZEN_KEY }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Setup Bun
        if: steps.opencode.outcome == 'success'
        uses: oven-sh/setup-bun@v2

      - name: Post triage
        if: steps.opencode.outcome == 'success'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          STRUCTURED_OUTPUT: ${{ steps.opencode.outputs.output }}
        run: |
          echo "$STRUCTURED_OUTPUT" > /tmp/triage-output.json
          bun run .github/scripts/submit-issue-triage.ts "${{ env.ISSUE_NUMBER }}" /tmp/triage-output.json
